"""商业运营服务的静态元数据。"""

from __future__ import annotations

from pathlib import Path
from typing import Any

COMMERCIAL_VERSION = "2.2.3"
DEMO_RESOURCE_GROUP_NAME = "commercial_trial_rg"
DEMO_USER_GROUP_NAME = "commercial_trial_team"
DEMO_APPROVAL_FLOW_NAME = "商业试用标准审批流"
DEMO_MARKER = "commercial_trial_bootstrap"
DELIVERY_MANIFEST_PATH = Path(__file__).resolve().parents[1] / "data" / "commercial_delivery_manifest.json"

ONBOARDING_STEPS = [
    {"key": "branding", "label": "品牌配置", "path": "/system/config"},
    {"key": "license", "label": "License 授权", "path": "/system/license"},
    {"key": "auth", "label": "认证方式", "path": "/system/config"},
    {"key": "notification", "label": "通知渠道", "path": "/system/config"},
    {"key": "first_instance", "label": "首个实例", "path": "/instance"},
    {"key": "governance", "label": "资源组/用户组/审批流", "path": "/system/groups"},
    {"key": "acceptance", "label": "验收报告", "path": "/commercial"},
]

RETENTION_DEFAULTS = {
    "operation_audit": 365,
    "query_history": 180,
    "notification_log": 90,
    "diagnostic_sampling": 30,
}

RETENTION_LABELS = {
    "operation_audit": "操作审计",
    "query_history": "查询历史",
    "notification_log": "通知日志",
    "diagnostic_sampling": "诊断采样",
}

DELIVERY_PREFLIGHT_DEFINITIONS: list[dict[str, Any]] = [
    {
        "key": "backup_script",
        "label": "备份脚本",
        "name": "备份脚本",
        "blocking": True,
        "kind": "executable",
        "paths": ["deploy/backup/backup-postgres.sh", "backup-postgres.sh"],
        "path": "/commercial",
    },
    {
        "key": "restore_script",
        "label": "恢复脚本",
        "name": "恢复脚本",
        "blocking": True,
        "kind": "executable",
        "paths": ["deploy/backup/restore-postgres.sh", "restore-postgres.sh"],
        "path": "/commercial",
    },
    {
        "key": "upgrade_script",
        "label": "升级回滚脚本",
        "name": "升级回滚脚本",
        "blocking": True,
        "kind": "executable",
        "paths": [
            "deploy/customer/upgrade.sh",
            f"dist-commercial/Sagitta-Control-v{COMMERCIAL_VERSION}/upgrade.sh",
            "upgrade.sh",
        ],
        "path": "/commercial",
    },
    {
        "key": "customer_go_live_scripts",
        "label": "客户上线脚本",
        "name": "客户上线脚本",
        "blocking": True,
        "kind": "all_executable",
        "paths": [
            "deploy/customer/prepare-go-live-env.sh",
            "deploy/customer/go-live-check.sh",
        ],
        "path": "/commercial",
    },
    {
        "key": "commercial_guard_scripts",
        "label": "商业构建门禁脚本",
        "name": "商业构建门禁脚本",
        "blocking": True,
        "kind": "all_executable",
        "paths": [
            "scripts/validate-commercial-build-context.sh",
            "scripts/validate-commercial-images.sh",
            "scripts/generate-commercial-sbom.sh",
            "scripts/sign-commercial-artifacts.sh",
        ],
        "path": "/commercial",
    },
    {
        "key": "customer_package_checksum",
        "label": "客户包 sha256",
        "name": "客户包 sha256",
        "blocking": False,
        "kind": "file",
        "paths": [f"dist-commercial/Sagitta-Control-v{COMMERCIAL_VERSION}.zip.sha256"],
        "path": "/commercial",
    },
    {
        "key": "customer_package_signature",
        "label": "客户包签名",
        "name": "客户包签名",
        "blocking": False,
        "kind": "file",
        "paths": [
            f"dist-commercial/Sagitta-Control-v{COMMERCIAL_VERSION}.zip.sig.json",
            f"dist-commercial/Sagitta-Control-v{COMMERCIAL_VERSION}.zip.asc",
            f"dist-commercial/Sagitta-Control-v{COMMERCIAL_VERSION}.zip.sig",
        ],
        "path": "/commercial",
    },
    {
        "key": "sbom_materials",
        "label": "SBOM 与签名材料",
        "name": "SBOM 与签名材料",
        "blocking": False,
        "kind": "glob",
        "paths": [
            "dist-commercial/sbom/*.cyclonedx.json",
            "dist-commercial/sbom/*.cyclonedx.json.sha256",
            "dist-commercial/sbom/*.cyclonedx.json.bundle",
        ],
        "path": "/commercial",
    },
]

ENGINE_MATRIX: list[dict[str, Any]] = [
    {
        "db_type": "mysql",
        "label": "MySQL",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": True,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": True,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "pgsql",
        "label": "PostgreSQL",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": True,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "tidb",
        "label": "TiDB",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": True,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "starrocks",
        "label": "StarRocks",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": True,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "clickhouse",
        "label": "ClickHouse",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": False,
            "monitor": True,
            "session": False,
            "explain": False,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "mongo",
        "label": "MongoDB",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": True,
            "monitor": True,
            "session": True,
            "explain": False,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "redis",
        "label": "Redis",
        "support_level": "ga",
        "support_label": "GA 正式支持",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": False,
            "archive": False,
            "monitor": True,
            "session": False,
            "explain": False,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "oracle",
        "label": "Oracle",
        "support_level": "validated_minimal",
        "support_label": "客户验证后交付",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": False,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "mssql",
        "label": "MSSQL",
        "support_level": "validated_minimal",
        "support_label": "客户验证后交付",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": False,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "doris",
        "label": "Doris",
        "support_level": "validated_minimal",
        "support_label": "客户验证后交付",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": True,
            "archive": False,
            "monitor": True,
            "session": True,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "elasticsearch",
        "label": "Elasticsearch",
        "support_level": "validated_minimal",
        "support_label": "客户验证后交付",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": False,
            "archive": False,
            "monitor": True,
            "session": False,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "opensearch",
        "label": "OpenSearch",
        "support_level": "validated_minimal",
        "support_label": "客户验证后交付",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": False,
            "archive": False,
            "monitor": True,
            "session": False,
            "explain": True,
            "kill_session": False,
        },
        "validation_required": "支持",
    },
    {
        "db_type": "cassandra",
        "label": "Cassandra/ScyllaDB",
        "support_level": "read_only_metadata",
        "support_label": "只读/元数据边界",
        "capabilities": {
            "connection": True,
            "schema": True,
            "query": True,
            "workflow": False,
            "archive": False,
            "monitor": True,
            "session": False,
            "explain": False,
            "kill_session": False,
        },
        "validation_required": "只读/元数据支持；SQL 洞察、DDL/DML/BATCH 不承诺",
    },
]
